#!/usr/bin/env bash

set -e

EA_PATH=$HOME/.emacs_everywhere

err () { echo -e "Error: $@" 1>&2; }

if [ ! -d $EA_PATH ]; then
    err emacs-everywhere is not installed
    exit 1
fi

rm -rf $EA_PATH

if [[ $OSTYPE == "darwin"* ]]; then
   rm -rf $HOME/Library/Services/Emacs\ Everywhere.workflow
fi

echo Emacs Everywhere has been uninstalled!
