#!/usr/bin/env bash

set -e

EA_PATH=$HOME/.emacs_everywhere

err () { echo -e "Error: $@" 1>&2; }

if [ ! -d $EA_PATH ]; then
    err Emacs Everywhere is not installed!
    exit 1
fi

pushd $EA_PATH
git pull origin master
popd

if [[ $OSTYPE == "darwin"* ]]; then
    cp -Rf $EA_PATH/Emacs\ Everywhere.workflow $HOME/Library/Services
fi

echo Emacs Everywhere has been updated!
